version: 2.1
jobs: 
  build:
    docker:
      - image: circleci/golang:1.15.5
    steps:
      - checkout
      - restore_cache:
          key: go-mod-v4-{{ checksum "go.sum" }}
      - run: npm install
      - save_cache:
          key: go-mod-v4-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"
      - run: go test -v