version: 2.1

executors:
  node-go:
    docker:
      - image: cimg/go:1.15.5-node
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD
      - image: circleci/postgres:9.6.2-alpine
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD
        environment:
          POSTGRES_USER: circle_user
          POSTGRES_DB: circle_db

jobs:
  build:
    executor: node-go
    working_directory: ~/project
    steps:
      - checkout
      - restore_cache:
          key: go-mod-v4-{{ checksum "go.sum" }}
      - save_cache:
          key: go-mod-v4-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"
      - run: 
          command: make build
  
  test:
    executor: node-go
    working_directory: ~/project
    steps:
      - checkout
      - run:
          command: make build-react
      - run: 
          environment:
            DATABASE_TEST_URL: "postgres://circle_user@localhost:5432/circle_db"
            SECRET_KEY: "shhh"
            PORT: "8000" 
          command: make test

workflows:
  version: 2

  build_and_test:
    jobs:
      - build
      - test