package mocks

import (
	"github.com/chumnend/pook/internal/pook/domain"
	"github.com/stretchr/testify/mock"
)

// UserRepository is an autogenerated mock type for the UserRepository type
type UserRepository struct {
	mock.Mock
}

// FindAll provides a mock function
func (mock *UserRepository) FindAll() ([]domain.User, error) {
	args := mock.Called()
	return args.Get(0).([]domain.User), args.Error(1)
}

// FindByEmail provides a mock function
func (mock *UserRepository) FindByEmail(email string) (*domain.User, error) {
	args := mock.Called(email)
	return args.Get(0).(*domain.User), args.Error(1)
}

// Save provides a mock function given a User struct
func (mock *UserRepository) Save(user *domain.User) error {
	args := mock.Called(user)
	return args.Error(0)
}
