package mocks

import (
	"github.com/chumnend/pook/internal/api/domain"
	"github.com/stretchr/testify/mock"
)

// MockService is an autogenerated mock type for the UserService type
type MockService struct {
	mock.Mock
}

// FindAll provides mock function
func (mock *MockService) FindAll() ([]domain.User, error) {
	args := mock.Called()
	return args.Get(0).([]domain.User), args.Error(1)
}

// FindByEmail provides mock function
func (mock *MockService) FindByEmail(email string) (*domain.User, error) {
	args := mock.Called(email)
	return args.Get(0).(*domain.User), args.Error(1)
}

// Save provides mock function
func (mock *MockService) Save(user *domain.User) error {
	args := mock.Called(user)
	return args.Error(0)
}

// Validate provides mock function
func (mock *MockService) Validate(user *domain.User) error {
	args := mock.Called(user)
	return args.Error(0)
}

// GenerateToken provides mock function
func (mock *MockService) GenerateToken(user *domain.User) (string, error) {
	args := mock.Called(user)
	return args.String(0), args.Error(1)
}

// ComparePassword provides mock function
func (mock *MockService) ComparePassword(user *domain.User, password string) error {
	args := mock.Called(user, password)
	return args.Error(0)
}
